#on: push
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
jobs:
    drata-iac-scan:
        runs-on: ubuntu-latest
        name: compliance-as-code-action
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Drata Github Action
          id: drata
          uses: drata/compliance-as-code-action@v0.0.102
          env:
              DRATA_API_TOKEN: ${{ secrets.DRATA_IAC_PIPELINE_KEY }}
              GITHUB_REPOSITORY: $GITHUB_REPOSITORY
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              minimumSeverity: 'HIGH'
